config/routes.rb
Dvd::Application.routes.draw do
  

  resources :customers
  resources :movies
  
  root "movies#index"

  devise_for :users

  namespace :admin do
    root "base#customers"
    get "movies", to: "base#movies"
    get "customers", to: "base#customers"
    resources :users
    
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :phone_number, presence: true
	validates :email, presence: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_attached_file :cover, :styles => { :medium => "600x600>", :thumb => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Pagination
  paginates_per 100

  # Validations
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def self.paged(page_number)
    order(admin: :desc, email: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      where("email LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, email: :asc
      ).page page_number
    else
      order(admin: :desc, email: :asc).page page_number
    end
  end

  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","email","created_at")
  end

  def self.last_signins(count)
    order(last_sign_in_at:
    :desc).limit(count).select("id","email","last_sign_in_at")
  end

  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :authenticate_user!
  before_filter :require_admin!

  def customers
  	@customers = Customer.paginate(:page => params[:page], :per_page => 16)
  end

  def movies 
  	@movies = Movie.paginate(:page => params[:page], :per_page => 10)
  	if params[:movie]
  		@movie = Movie.find(params[:movie])
  	else
  		@movie = Movie.new
  	end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]

  
  def index
    @users = User.search_and_order(params[:search], params[:page])
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def edit
  end

  def update
    old_email = @user.email
    new_params = user_params.dup
    new_params[:email] = new_params[:email].strip

    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0

    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end

    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} updated."
    else
      flash[:alert] = "#{old_email} couldn't be updated."
      render :edit
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :reject_locked!, if: :devise_controller?

  # Devise permitted params
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
      :email,
      :password,
      :password_confirmation)
    }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
      :email,
      :password,
      :password_confirmation,
      :current_password
      )
    }
  end

  # Redirects on successful sign in
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  # Auto-sign out locked users
  def reject_locked!
    if current_user && current_user.locked?
      sign_out current_user
      user_session = nil
      current_user = nil
      flash[:alert] = "Your account is locked."
      flash[:notice] = nil
      redirect_to root_url
    end
  end
  helper_method :reject_locked!

  # Only permits admin users
  def require_admin!
    authenticate_user!

    if current_user && !current_user.admin?
      redirect_to root_path
    end
  end
  helper_method :require_admin!

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:destroy]

  # POST /customers
  def create
    @movie = Movie.find(params[:movie])
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to movie_path(id: @movie.id, customer: @customer.id), notice: 'Customer was successfully created.' }
      else
        format.html { render "movies/show" }
      end
    end
  end


  # DELETE /customers/1
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to admin_root_path, notice: 'Customer was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone_number, :email)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.paginate(:page => params[:page], :per_page => 16)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    if params[:customer]
      @customer = Customer.find(params[:customer])
    else
      @customer = Customer.new
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to admin_movies_path, notice: 'Movie was successfully created.' }
      else
        format.html { redirect_to admin_movies_path }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to admin_movies_path, notice: 'Movie was successfully updated.' }
      else
        format.html { redirect_to admin_movies_path }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_path, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Dvd"
    end
  end
end

app/helpers/email_helper.rb
module EmailHelper
  def line_break(s)
    s.gsub("\n", "<br/>")
  end
end

app/views/admin/base/customers.html.erb
<h3>Lastest Customers</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name string</th>
      <th>Phone number</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
    <%= will_paginate @customers, renderer: BootstrapPagination::Rails %>
  </div>

app/views/admin/base/movies.html.erb
<div class="row">
  <div class="col-md-6">
  <h3>Movies</h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Curated at</th>
        <th>Title</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.created_at %></td>
          <td><%= movie.title %></td>
          <td><%= link_to "Edit", admin_movies_path(movie: movie.id) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @movies, renderer: BootstrapPagination::Rails %>
  </div>
  </div>
  <div class="col-md-6">
    <% if @movie.id == nil %>
      <h3>New Movie</h3>
    <% else %>
      <h3><%= "Edit #{@movie.title}" %></h3>
    <% end %>
    <%= render "movies/form" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% title("Edit User Id: #{@user.id}") %>
<div class="row">
  <div class="col-sm-6">
    <h1>
      Edit User <small><%= "#{@user.email} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>

    <% unless current_user.id == @user.id %>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
        </div>
      </div>
    </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update User", class: "btn btn-danger" %>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<% title("Users Admin") %>
<h1>Users <small>Admin</small></h1>
<p><%= link_to "Back to Admin", admin_root_path %></p>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>User ID</th>
    <th>Admin</th>
    <th>Locked</th>
    <th>Email</th>
    <th>Sign In Count</th>
    <th>Created At</th>
    <th>Last Sign In</th>
    <th>Last Sign In IP</th>
  </tr>

  <% @users.each do |user| %>

  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.email, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
    <td><%= user.last_sign_in_ip %></td>
  </tr>

  <% end %>

</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>

<p> <%= "Provide your data in order to rent #{@movie.title}" %></p>
      <% if @customer.errors.any? %>
    <div id="error_explanation">
      <strong class="text-danger">Sorry but there were some errors</strong>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <hr>
    </div>
  <% end %>

      <%= hidden_field_tag 'movie', @movie.id  %>

      <div class="form-group">
        <%= f.label :first_name, class: "control-label" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :last_name, class: "control-label" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :phone_number, class: "control-label" %>
        <%= f.text_field :phone_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "control-label" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <%= f.submit "Rent #{@movie.title}", class: "btn btn-success" %>

    <% end %>

app/views/customers/_index.html.erb
<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name string</th>
      <th>Phone number</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name_string %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - Yourself!
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= movies_path %>">DVDrent</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
            <li><a href="../navbar-static-top/">Contact</a></li>
            <li><%= link_to "Admin", admin_root_path %></li>
        <% else %>
            <li><%= link_to "Customers", admin_customers_path %></li>
             <li><%= link_to "Movies", admin_movies_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
<li><%= link_to "Protected Page", inside_path %></li>
<li><%= link_to "Edit your account", edit_user_registration_path %></li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Dvd" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>



</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :multipart => true } do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title ,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: 7 %>
  </div>
  <div class="form-group">
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-default" %>
  </div>
  <div class="action" style="margin-top:10px">
    <%= link_to "Abort",  admin_movies_path, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>


  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.description %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/movies/index.html.erb
<% @movies.each_slice(4) do |slice| %>
  <div class="row">
    <% slice.each do |movie| %>
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= movie.title %>
          </div>
          <div class="panel-body" style="padding:0px">
            <%= image_tag movie.cover.url(:thumb), width: '100%', height: 'auto' %>
           <div class="panel-footer text-center">
              <%= link_to "Rent!", movie_path(movie) %>
           </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>



<div class="row">
  <div class="text-center">
    <%= will_paginate @movies, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="row">
	<div class="col-md-12">
		<h1><%= @movie.title %></h1>
	</div> 
</div>

<div class="row">
	<div class="col-md-3">
		<%= image_tag @movie.cover.url(:medium), width: '100%', height: 'auto', style: "border-radius:40px" %>
	</div>
	<div class="col-md-4">
		<h4><strong>Description:</strong></h4>
		<p>
		<%= @movie.description %></p>
	</div>
	<div class="col-md-5">
		<% if @customer.id == nil %>
			<h4><strong>Rent Now!</strong></h4>
			<%= render "customers/form" %>
		<% else %>
			<h4 class="text-success"><%= "Hi, #{@customer.first_name}!" %></h4>
			<p> please pick up your movie at the following location:</p>

			<strong>1132 Fort Street mall</strong>
			<br>
			<strong>Honolulu, Hi</strong>
			<br>
			<br>
			<p>If you have additional questions, give us a call:</p>

			<strong>tel 808-797-6070</strong>
			<br>
			<br>
				<%= link_to 'Take me back to Movies List', movies_path, class: "btn btn-success" %>
		<% end %>
	</div>
</div>

<% if @customer.id == nil %>
<div class="row">
	<div class="col-md-12">
		<%= link_to 'Go Back', movies_path, class: "btn btn-default" %>
	</div>
</div>

<% end %>